version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:    
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"     
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    restart: always

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro    
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro 
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always
  
  nginx:
    build:
      context: nginx/
    ports:
      - "80:80"   
      - "443:443"
      - "5000:5000"
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - KIBANA_USERNAME=${KIBANA_USERNAME}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    volumes:
      - ./nginx/logs:/var/log/nginx/
      - "./nginx/certificate/kibana.crt:/etc/nginx/ssl/kibana.crt"
      - "./nginx/certificate/kibana.key:/etc/nginx/ssl/kibana.key"
      - "./nginx/certificate/dhparam.pem:/etc/nginx/ssl/dhparam.pem"
      - "./nginx/certificate/logstash.crt:/etc/nginx/ssl/logstash.crt"
      - "./nginx/certificate/logstash.key:/etc/nginx/ssl/logstash.key"
      - ./nginx/data/letsencrypt:/data/letsencrypt/     
    networks:
      - elk
    depends_on:
      - kibana
    restart: always

volumes:
  elasticdata:
    driver: local

networks:
  elk:
    driver: bridge
